### ISSUE TITLE
Linux compatibility issues

### ISSUE THREAD

**Issue by Daxorinator** [fearghal1/HDLGen-ChatGPT#42]
Version: Commit #ab58e30 on Master

OS: Debian 11 (Windows Subsystem for Linux)
Python Version: Python 3.10.7 from Python.org

Issue: No predefined Types or Subcomponents appear on Linux-based systems
Behaviour: Clicking on "Types" in "HDL Designer" does not show any predefined types
Expected Behaviour: Clicking on "Types" in "HDL Designer" _does_ show the predefined types as on Windows

Issue: Cannot add Ports (Combinational) on Linux
Behaviour: In "HDL Designer", under "Ports", clicking "Add Signal" does not open the "Add Signal" dialogue box
Expected Behaviour: The "Add Signal" Dialogue box should open

Issue: Cannot add Internal Signals on Linux
Behaviour: In "HDL Designer", under "Internal Signals" clicking on "Add Signal" does not open the "Add Signal" dialogue box
Expected Behaviour: The "Add Signal" Dialogue box should open

Issue is known to be affecting Linux and Windows Subsystem for Linux users on most common distributions.

**Comment by Daxorinator** [comment]
I've identified why this is I believe:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/crash/HDLGen-ChatGPT/User_Projects\\Package\\MainPackage.hdlgen'
Traceback (most recent call last):
  File "/home/crash/HDLGen-ChatGPT/Application/HDLDesigner/IOPorts/io_ports.py", line 218, in add_signal
    io_dialog = IOPortDialog("add", self.all_signals_names)
  File "/home/crash/HDLGen-ChatGPT/Application/HDLDesigner/IOPorts/io_port_dialog.py", line 114, in __init__
    root = minidom.parse(mainPackageDir)
```

As can be seen here, the application appears to be treating the path as if it were a Windows path. The part at the end, `\\Package\\MainPackage.hdlgen` appears to be hardcoded in a few places and causes Python to trip up due to the combination of Windows and Linux file paths.
